services:
  database:
    build: ./database
    container_name: burger-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: burger-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: burgerbuilder
      DB_USERNAME: postgres
      DB_PASSWORD: YourStrong!Passw0rd
      DB_DRIVER: org.postgresql.Driver
      SERVER_PORT: 8080
      CORS_ALLOWED_ORIGINS: http://192.168.0.106:5173
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://192.168.0.106:8080
    container_name: burger-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
